### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by nagusa** [HiPrecy/Firmware-HiPrecy#1]
I get this error if i compile the marlin for the f6.

sketch\src\MarlinCore.cpp:185:12: fatal error: feature/first_lay_cal.h: No such file or directory

#include "feature/first_lay_cal.h"

^~~~~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

exit status 1

Fehler beim Kompilieren für das Board FYSETC_F6.

**Comment by GiliFuuu** [comment]
Thanks for report. It's beed fix in the new commit.
